// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuilqikbakoyydfrjggt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1aWxxaWtiYWtveXlkZnJqZ2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDMzMDYsImV4cCI6MjA1OTQxOTMwNn0.sL3Ef-D-UyxIVsISae7gIfXdZn0zIhFzQ-FnbsiBep0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);